name: github-action
run-name: ${{ github.actor }} is out building GitHub Actions

on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '**' 

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build Maven Projects
        run: |
          mvn clean package -f ./ramenorder/pom.xml
          mvn clean package -f ./ramencook/pom.xml
          mvn clean package -f ./delivery/pom.xml

      - name: Docker Build and push for Ramenorder
        uses: docker/build-push-action@v4
        with:
          context: ./ramenorder
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/ramenorder:latest
            ghcr.io/${{ github.repository }}/ramenorder:${{ github.ref_name }}
            
      - name: Docker Build and push for Ramencook
        uses: docker/build-push-action@v4
        with:
          context: ./ramencook
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/ramencook:latest
            ghcr.io/${{ github.repository }}/ramencook:${{ github.ref_name }}
            
      - name: Docker Build and push for Delivery
        uses: docker/build-push-action@v4
        with:
          context: ./delivery
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/delivery:latest
            ghcr.io/${{ github.repository }}/delivery:${{ github.ref_name }}
            
