apiVersion: apps/v1
kind: Deployment
metadata:
  name: ramencook
  labels:
    app: ramencook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ramencook
  template:
    metadata:
      labels:
        app: ramencook
    spec:
      containers:
        - name: ramencook
          image: "username/ramencook:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
