---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ramenorder
  labels:
    app: ramenorder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ramenorder
  template:
    metadata:
      labels:
        app: ramenorder
    spec:
      containers:
        - name: ramenorder
          image: username/ramenorder:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ramencook
  labels:
    app: ramencook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ramencook
  template:
    metadata:
      labels:
        app: ramencook
    spec:
      containers:
        - name: ramencook
          image: username/ramencook:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery
  labels:
    app: delivery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: delivery
  template:
    metadata:
      labels:
        app: delivery
    spec:
      containers:
        - name: delivery
          image: username/delivery:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: ramenorder
  labels:
    app: ramenorder
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: ramenorder


---


apiVersion: v1
kind: Service
metadata:
  name: ramencook
  labels:
    app: ramencook
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: ramencook


---


apiVersion: v1
kind: Service
metadata:
  name: delivery
  labels:
    app: delivery
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: delivery

